[workspace]
authors = ["Douglas Yu <dougwyu@mac.com>"]
channels = ["conda-forge", "https://conda.anaconda.org/pytorch", "https://conda.modular.com/max"]
name = "port-feasibility"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=1.0.0,<2"
max = ">=26.5.0,<27"
pytorch = { version = ">=2.5.1,<3", channel = "pytorch" }

[pypi-dependencies]
pytest = ">=9.1.1, <10"
pyro-ppl = ">=1.9.1, <2"
torch-optimizer = ">=0.3.0, <0.4"
madgrad = ">=1.3, <2"
tqdm = ">=4.70.0, <5"
